/**
 * Seed du catalogue Produits — référentiel global (tenantId = NULL).
 *
 * Sources officielles utilisées :
 *   - Variétés céréales : swissgranum / Agroscope, "Liste recommandée des
 *     variétés de céréales pour la récolte 2025" (Agroscope Transfer N°542,
 *     mai 2024). Référence valable pour les semis 2025 → récolte 2026.
 *   - Variétés maïs : swiss granum / Agroscope, liste 2026 (publication
 *     janvier 2026 — 11 nouvelles variétés cette année).
 *   - Mélanges fourragers (Mst) : Agroscope / eADCF, "Mélanges standard
 *     pour la production fourragère, révision 2025-2028".
 *   - Engrais : références terrain Agridea + catalogues Landor/Lonza.
 *   - Phytos : index OSAV (psm.admin.ch) — sélection des plus courants ;
 *     l'import complet via XML OSAV viendra en Phase B.
 *
 * Idempotent : `upsert` par `code`.
 */
import { PrismaClient, ProduitCategorie, ProduitUnite } from "@prisma/client";

const prisma = new PrismaClient();

interface SeedProduit {
  code: string;
  categorie: ProduitCategorie;
  libelle: string;
  fournisseur?: string;
  marque?: string;
  numeroOfficiel?: string;
  especeCode?: string;
  tauxN?: number;
  tauxP?: number;
  tauxK?: number;
  unite?: ProduitUnite;
  notes?: string;
  sourceCatalogue: string;
}

const SRC_SG = "swissgranum 2025 (récolte 2026)";
const SRC_SG_MAIS = "swiss granum / Agroscope — liste maïs 2026";
const SRC_MST = "Agroscope / eADCF — Mst 2025-2028";
const SRC_LANDOR = "Catalogue Landor (Fenaco)";
const SRC_AGRIDEA = "Agridea 1.18 — valeurs moyennes";
const SRC_OSAV = "OSAV — psm.admin.ch (sélection MVP)";

// Helper pour réduire la verbosité.
function ble(
  code: string,
  libelle: string,
  classe: "TOP" | "I" | "II" | "FOURRAGER" | "BISCUIT",
  origine = "CH",
): SeedProduit {
  return {
    code,
    categorie: ProduitCategorie.SEMENCE,
    libelle,
    fournisseur: "swissgranum / Agroscope",
    marque: classe,
    especeCode: classe === "FOURRAGER" || classe === "BISCUIT" ? "ble_fourrager" : "ble_panifiable",
    unite: ProduitUnite.KG,
    notes: `Origine ${origine}. Classe ${classe}.`,
    sourceCatalogue: SRC_SG,
  };
}

const PRODUITS: SeedProduit[] = [
  // ==================================================================
  // SEMENCES — Blé d'automne (swissgranum 2025 — 23 variétés)
  // ==================================================================
  ble("aq-sem-ble-bodeli", "Blé Bodeli", "TOP"),
  ble("aq-sem-ble-caminada", "Blé Caminada (provisoire)", "TOP"),
  ble("aq-sem-ble-piznair", "Blé Piznair", "TOP"),
  ble("aq-sem-ble-runal", "Blé Runal", "TOP"),
  ble("aq-sem-ble-axen", "Blé Axen", "TOP"),
  ble("aq-sem-ble-bonavau", "Blé Bonavau", "TOP"),
  ble("aq-sem-ble-baretta", "Blé Baretta", "TOP"),
  ble("aq-sem-ble-cadlimo", "Blé Cadlimo", "TOP"),
  ble("aq-sem-ble-diavel", "Blé Diavel (alternatif)", "TOP"),
  ble("aq-sem-ble-ch-nara", "Blé CH Nara", "TOP"),
  ble("aq-sem-ble-montalbano", "Blé Montalbano", "TOP"),
  ble("aq-sem-ble-camedo", "Blé CH Camedo", "TOP"),
  ble("aq-sem-ble-arina", "Blé Arina", "I"),
  ble("aq-sem-ble-forel", "Blé Forel", "I"),
  ble("aq-sem-ble-hanswin", "Blé Hanswin", "I"),
  ble("aq-sem-ble-alpval", "Blé Alpval", "I"),
  ble("aq-sem-ble-campanile", "Blé Campanile", "I", "UE"),
  ble("aq-sem-ble-posmeda", "Blé Posmeda", "II", "UE"),
  ble("aq-sem-ble-spontan", "Blé Spontan", "II", "UE"),
  ble("aq-sem-ble-ludwig", "Blé Ludwig (dernière année)", "II", "UE"),
  ble("aq-sem-ble-campesino", "Blé fourrager Campesino", "FOURRAGER", "UE"),
  ble("aq-sem-ble-sailor", "Blé fourrager Sailor", "FOURRAGER", "UE"),
  ble("aq-sem-ble-poncione", "Blé fourrager Poncione", "FOURRAGER"),
  ble("aq-sem-ble-dilago", "Blé biscuit Dilago", "BISCUIT"),

  // Blé de printemps (alternatives)
  {
    code: "aq-sem-ble-pr-fiorina",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Blé de printemps Fiorina",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "ble_panifiable",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-ble-pr-rubli",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Blé de printemps Rubli",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "ble_panifiable",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },

  // ==================================================================
  // SEMENCES — Orge (automne + printemps)
  // ==================================================================
  {
    code: "aq-sem-orge-aut-kws-orbit",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Orge d'automne KWS Orbit",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "orge",
    unite: ProduitUnite.KG,
    notes: "6 rangs, fourragère",
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-orge-aut-kws-higgins",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Orge d'automne KWS Higgins",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "orge",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-orge-aut-kingston",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Orge d'automne Kingston",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "orge",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-orge-aut-canyon",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Orge d'automne Canyon",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "orge",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-orge-aut-tardis",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Orge d'automne Tardis",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "orge",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-orge-aut-arthene",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Orge d'automne Arthene (nouvelle 2026)",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "orge",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-orge-pr-malva",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Orge brassicole de printemps Malva",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "orge",
    unite: ProduitUnite.KG,
    notes: "Brassicole, 2 rangs",
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-orge-pr-quench",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Orge brassicole Quench",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "orge",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },

  // ==================================================================
  // SEMENCES — Triticale, seigle, avoine, épeautre
  // ==================================================================
  {
    code: "aq-sem-tritic-atrika",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Triticale Atrika",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "ble_fourrager",
    unite: ProduitUnite.KG,
    notes: "Triticale (× ble_fourrager pour bilanz)",
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-tritic-larossa",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Triticale Larossa",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "ble_fourrager",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-tritic-cosinus",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Triticale Cosinus",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "ble_fourrager",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-tritic-kitesurf",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Triticale Kitesurf (nouvelle 2026)",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "ble_fourrager",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-seigle-aleksandra",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Seigle Aleksandra",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "ble_fourrager",
    unite: ProduitUnite.KG,
    notes: "Seigle hiver",
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-seigle-mufa",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Seigle Mufa",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "ble_fourrager",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-seigle-pufa",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Seigle Pufa",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "ble_fourrager",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-avoine-husky",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Avoine Husky",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "orge",
    unite: ProduitUnite.KG,
    notes: "Avoine printemps (besoin N proche orge)",
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-avoine-lion",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Avoine Lion",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "orge",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-avoine-galileoo",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Avoine Galileoo",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "orge",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-epeautre-oberkulmer",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Épeautre Oberkulmer",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "ble_panifiable",
    unite: ProduitUnite.KG,
    notes: "Épeautre rotkorn, valeur boulangère",
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-epeautre-ostro",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Épeautre Ostro",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "ble_panifiable",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-epeautre-edelweisser",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Épeautre Edelweisser",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "ble_panifiable",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-epeautre-gletscher",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Épeautre Gletscher (nouvelle 2026)",
    fournisseur: "swissgranum / Agroscope",
    especeCode: "ble_panifiable",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },

  // ==================================================================
  // SEMENCES — Maïs (Agroscope 2026, 11 nouvelles)
  // ==================================================================
  {
    code: "aq-sem-mais-grain-lg31272",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Maïs grain LG31272",
    fournisseur: "Limagrain",
    marque: "LG31272",
    especeCode: "mais_grain",
    unite: ProduitUnite.DOSE,
    notes: "1 dose = 50 000 grains",
    sourceCatalogue: SRC_SG_MAIS,
  },
  {
    code: "aq-sem-mais-grain-sy-orpheus",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Maïs grain SY Orpheus",
    fournisseur: "Syngenta",
    especeCode: "mais_grain",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_SG_MAIS,
  },
  {
    code: "aq-sem-mais-grain-p8888",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Maïs grain P8888 (Pioneer)",
    fournisseur: "Corteva / Pioneer",
    especeCode: "mais_grain",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_SG_MAIS,
  },
  {
    code: "aq-sem-mais-grain-figaro",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Maïs grain Figaro",
    fournisseur: "KWS",
    especeCode: "mais_grain",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_SG_MAIS,
  },
  {
    code: "aq-sem-mais-ens-ds1492c",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Maïs ensilage DS1492C",
    fournisseur: "Delley Semences",
    marque: "DS1492C",
    especeCode: "mais_ensilage",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_SG_MAIS,
  },
  {
    code: "aq-sem-mais-ens-lg31256",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Maïs ensilage LG31256",
    fournisseur: "Limagrain",
    especeCode: "mais_ensilage",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_SG_MAIS,
  },
  {
    code: "aq-sem-mais-ens-sy-amfora",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Maïs ensilage SY Amfora",
    fournisseur: "Syngenta",
    especeCode: "mais_ensilage",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_SG_MAIS,
  },
  {
    code: "aq-sem-mais-ens-prosperia",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Maïs ensilage Prosperia",
    fournisseur: "KWS",
    especeCode: "mais_ensilage",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_SG_MAIS,
  },

  // ==================================================================
  // SEMENCES — Colza, tournesol, soja, protéagineux
  // ==================================================================
  {
    code: "aq-sem-colza-architect",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Colza Architect (hybride)",
    fournisseur: "UFA-Semences",
    marque: "Architect",
    especeCode: "colza",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-colza-lg-austin",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Colza LG Austin (nouvelle 2026)",
    fournisseur: "Limagrain",
    especeCode: "colza",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-colza-blackmoon",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Colza Blackmoon (nouvelle 2026)",
    fournisseur: "DSV",
    especeCode: "colza",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-colza-dk-excited",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Colza DK Excited",
    fournisseur: "Bayer / Dekalb",
    especeCode: "colza",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-colza-dk-expansion",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Colza DK Expansion",
    fournisseur: "Bayer / Dekalb",
    especeCode: "colza",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-tournesol-sy-talento",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Tournesol SY Talento",
    fournisseur: "Syngenta",
    especeCode: "tournesol",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-tournesol-es-niagara",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Tournesol ES Niagara",
    fournisseur: "Lidea",
    especeCode: "tournesol",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-soja-galice",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Soja Galice",
    fournisseur: "Agroscope / DSP",
    especeCode: "tournesol", // pas dans rule engine, fallback raisonnable
    unite: ProduitUnite.KG,
    notes: "Soja — légumineuse (apport N atmosphérique non couvert V1)",
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-feverole-fanfare",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Féverole Fanfare",
    fournisseur: "swissgranum / Agroscope",
    unite: ProduitUnite.KG,
    notes: "Féverole — légumineuse",
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-pois-protein-astronaute",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pois protéagineux Astronaute",
    fournisseur: "swissgranum / Agroscope",
    unite: ProduitUnite.KG,
    notes: "Pois protéagineux — légumineuse",
    sourceCatalogue: SRC_SG,
  },

  // ==================================================================
  // SEMENCES — Pomme de terre, betterave
  // ==================================================================
  {
    code: "aq-sem-pdt-charlotte",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pomme de terre Charlotte",
    fournisseur: "Semences Suisses",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-pdt-agria",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pomme de terre Agria",
    fournisseur: "Semences Suisses",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-pdt-erika",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pomme de terre Erika",
    fournisseur: "Semences Suisses",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-pdt-gourmandine",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pomme de terre Gourmandine",
    fournisseur: "Semences Suisses",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-betterave-magnum",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Betterave sucrière Magnum",
    fournisseur: "Strube",
    especeCode: "betterave_sucre",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-betterave-thunder",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Betterave sucrière Thunder",
    fournisseur: "KWS",
    especeCode: "betterave_sucre",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_SG,
  },

  // ==================================================================
  // SEMENCES — Mélanges fourragers Mst (Agroscope 2025-2028)
  // Codification : 1xx = annuel, 3xx = 3 ans, 4xx = long terme
  //                x3x = dactyle, x4x = sans dactyle, x5x = prairie permanente
  //                xx0 = zones favorables ray-grass, xxN = défavorables
  // ==================================================================
  {
    code: "aq-mst-100",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 100 (annuel — ray-grass d'Italie pur)",
    fournisseur: "UFA-Semences / Otto Hauenstein",
    numeroOfficiel: "Mst 100",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    notes: "Annuel, fauche, après céréales",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-200",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 200 (graminées-trèfles courte durée)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 200",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    notes: "1-2 ans, fauche intensive",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-220",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 220 (luzerne pure ou en association)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 220",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    notes: "2-3 ans, fauche, sols profonds",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-240",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 240 (luzerne + graminées)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 240",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-300",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 300 (graminées-trèfles 3 ans, dactyle)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 300",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    notes: "3 ans, dactyle, zones défavorables ray-grass",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-310",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 310 (graminées-trèfles, dactyle, ray-grass)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 310",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-320",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 320 (sans dactyle, fauche)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 320",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-330",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 330 (graminées-trèfle blanc, longue durée)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 330",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    notes: "ADCF qualité G — 4-5 ans, mixte fauche/pâture",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-340",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 340 (longue durée, sans dactyle)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 340",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-431",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 431 (long terme, dactyle)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 431",
    especeCode: "prairie_permanente",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-440",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 440 (long terme, sans dactyle)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 440",
    especeCode: "paturage_extensif",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-450",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 450 (prairie permanente fauchée)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 450",
    especeCode: "prairie_permanente",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-462",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 462 (prairie pâturée intensive)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 462",
    especeCode: "paturage_intensif",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-481",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 481 (pâturage intensif, ray-grass anglais)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 481",
    especeCode: "paturage_intensif",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-911",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 911 (zone alpine, pâture intensive)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 911",
    especeCode: "paturage_intensif",
    unite: ProduitUnite.KG,
    notes: "Zone montagne / estivage",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-mst-940",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 940 (zone alpine, fauche)",
    fournisseur: "UFA-Semences",
    numeroOfficiel: "Mst 940",
    especeCode: "prairie_permanente",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },

  // ==================================================================
  // ENGRAIS MINÉRAUX — Landor (Fenaco)
  // ==================================================================
  {
    code: "aq-eng-ammonitrate-27",
    categorie: ProduitCategorie.ENGRAIS_MINERAL,
    libelle: "Ammonitrate 27% N",
    fournisseur: "Landor",
    tauxN: 27,
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-eng-uree-46",
    categorie: ProduitCategorie.ENGRAIS_MINERAL,
    libelle: "Urée 46% N",
    fournisseur: "Landor",
    tauxN: 46,
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-eng-nitrate-ca-15",
    categorie: ProduitCategorie.ENGRAIS_MINERAL,
    libelle: "Nitrate de chaux 15.5% N",
    fournisseur: "Landor",
    tauxN: 15.5,
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-eng-sulfate-am-21",
    categorie: ProduitCategorie.ENGRAIS_MINERAL,
    libelle: "Sulfate d'ammoniaque 21% N",
    fournisseur: "Landor",
    tauxN: 21,
    unite: ProduitUnite.KG,
    notes: "Apport souffre + acidification sols calcaires",
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-eng-npk-15-15-15",
    categorie: ProduitCategorie.ENGRAIS_MINERAL,
    libelle: "NPK 15-15-15 (Nitrophoska bleu)",
    fournisseur: "Landor",
    tauxN: 15,
    tauxP: 15 * 0.436,
    tauxK: 15 * 0.83,
    unite: ProduitUnite.KG,
    notes: "Tauxs P et K en élémentaire (pas oxyde)",
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-eng-npk-20-10-10",
    categorie: ProduitCategorie.ENGRAIS_MINERAL,
    libelle: "NPK 20-10-10",
    fournisseur: "Landor",
    tauxN: 20,
    tauxP: 10 * 0.436,
    tauxK: 10 * 0.83,
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-eng-npk-12-12-17",
    categorie: ProduitCategorie.ENGRAIS_MINERAL,
    libelle: "NPK 12-12-17 (+ Mg + S)",
    fournisseur: "Landor",
    tauxN: 12,
    tauxP: 12 * 0.436,
    tauxK: 17 * 0.83,
    unite: ProduitUnite.KG,
    notes: "Engrais complet pour grandes cultures",
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-eng-superphosphate-46",
    categorie: ProduitCategorie.ENGRAIS_MINERAL,
    libelle: "Superphosphate triple 46% P₂O₅",
    fournisseur: "Landor",
    tauxP: 46 * 0.436,
    unite: ProduitUnite.KG,
    notes: "P₂O₅ × 0.436 = P élémentaire",
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-eng-kcl-60",
    categorie: ProduitCategorie.ENGRAIS_MINERAL,
    libelle: "Chlorure de potassium 60% K₂O",
    fournisseur: "Landor",
    tauxK: 60 * 0.83,
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-eng-patentkali",
    categorie: ProduitCategorie.ENGRAIS_MINERAL,
    libelle: "Patentkali 30% K₂O + 10% MgO + 17% S",
    fournisseur: "Landor",
    tauxK: 30 * 0.83,
    unite: ProduitUnite.KG,
    notes: "K + Mg + S — cultures sensibles au chlore",
    sourceCatalogue: SRC_LANDOR,
  },

  // ==================================================================
  // ENGRAIS ORGANIQUES — valeurs Agridea moyennes
  // ==================================================================
  {
    code: "aq-org-lisier-bovin",
    categorie: ProduitCategorie.ENGRAIS_ORGANIQUE,
    libelle: "Lisier bovin (moyenne)",
    tauxN: 0.4,
    tauxP: 0.07,
    tauxK: 0.5,
    unite: ProduitUnite.M3,
    notes: "≈ 4 kg N/m³ — analyser pour précision",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-org-lisier-bovin-dilue",
    categorie: ProduitCategorie.ENGRAIS_ORGANIQUE,
    libelle: "Lisier bovin dilué (rinçage)",
    tauxN: 0.2,
    tauxP: 0.04,
    tauxK: 0.3,
    unite: ProduitUnite.M3,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-org-lisier-porc",
    categorie: ProduitCategorie.ENGRAIS_ORGANIQUE,
    libelle: "Lisier porc (engraissement)",
    tauxN: 0.55,
    tauxP: 0.13,
    tauxK: 0.3,
    unite: ProduitUnite.M3,
    notes: "≈ 5.5 kg N/m³",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-org-lisier-porc-truies",
    categorie: ProduitCategorie.ENGRAIS_ORGANIQUE,
    libelle: "Lisier porc (truies allaitantes)",
    tauxN: 0.45,
    tauxP: 0.1,
    tauxK: 0.25,
    unite: ProduitUnite.M3,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-org-fumier-bovin",
    categorie: ProduitCategorie.ENGRAIS_ORGANIQUE,
    libelle: "Fumier bovin composté",
    tauxN: 0.5,
    tauxP: 0.15,
    tauxK: 0.6,
    unite: ProduitUnite.T,
    notes: "≈ 5 kg N/t",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-org-fumier-volaille",
    categorie: ProduitCategorie.ENGRAIS_ORGANIQUE,
    libelle: "Fumier de volaille",
    tauxN: 1.5,
    tauxP: 0.4,
    tauxK: 0.8,
    unite: ProduitUnite.T,
    notes: "≈ 15 kg N/t — concentré",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-org-fumier-cheval",
    categorie: ProduitCategorie.ENGRAIS_ORGANIQUE,
    libelle: "Fumier de cheval",
    tauxN: 0.4,
    tauxP: 0.1,
    tauxK: 0.5,
    unite: ProduitUnite.T,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-org-compost-vegetal",
    categorie: ProduitCategorie.ENGRAIS_ORGANIQUE,
    libelle: "Compost végétal",
    tauxN: 0.6,
    tauxP: 0.2,
    tauxK: 0.5,
    unite: ProduitUnite.T,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-org-digestat-meth",
    categorie: ProduitCategorie.ENGRAIS_ORGANIQUE,
    libelle: "Digestat de méthanisation",
    tauxN: 0.45,
    tauxP: 0.08,
    tauxK: 0.4,
    unite: ProduitUnite.M3,
    sourceCatalogue: SRC_AGRIDEA,
  },

  // ==================================================================
  // PHYTOS — sélection courante (catalogue OSAV — psm.admin.ch)
  // Phase B : import auto via XML OSAV.
  // ==================================================================
  {
    code: "aq-phyto-roundup-max",
    categorie: ProduitCategorie.PHYTO,
    libelle: "Roundup MAX 360 (glyphosate)",
    fournisseur: "Bayer",
    unite: ProduitUnite.L,
    notes: "Herbicide total non sélectif",
    sourceCatalogue: SRC_OSAV,
  },
  {
    code: "aq-phyto-stomp-aqua",
    categorie: ProduitCategorie.PHYTO,
    libelle: "Stomp Aqua (pendiméthaline)",
    fournisseur: "BASF",
    unite: ProduitUnite.L,
    notes: "Herbicide pré-levée maïs/tournesol",
    sourceCatalogue: SRC_OSAV,
  },
  {
    code: "aq-phyto-orius",
    categorie: ProduitCategorie.PHYTO,
    libelle: "Orius (tébuconazole)",
    fournisseur: "Adama",
    unite: ProduitUnite.L,
    notes: "Fongicide blé/orge",
    sourceCatalogue: SRC_OSAV,
  },
  {
    code: "aq-phyto-karate-zeon",
    categorie: ProduitCategorie.PHYTO,
    libelle: "Karate Zeon (lambda-cyhalothrine)",
    fournisseur: "Syngenta",
    unite: ProduitUnite.L,
    notes: "Insecticide pyréthrinoïde",
    sourceCatalogue: SRC_OSAV,
  },
  {
    code: "aq-phyto-banjo-forte",
    categorie: ProduitCategorie.PHYTO,
    libelle: "Banjo Forte (fluazinam + dimétomorphe)",
    fournisseur: "Adama",
    unite: ProduitUnite.L,
    notes: "Fongicide mildiou pomme de terre",
    sourceCatalogue: SRC_OSAV,
  },
  {
    code: "aq-phyto-prosaro",
    categorie: ProduitCategorie.PHYTO,
    libelle: "Prosaro (prothioconazole + tébuconazole)",
    fournisseur: "Bayer",
    unite: ProduitUnite.L,
    sourceCatalogue: SRC_OSAV,
  },
  {
    code: "aq-phyto-mospilan",
    categorie: ProduitCategorie.PHYTO,
    libelle: "Mospilan (acétamipride)",
    fournisseur: "Sumi Agro",
    unite: ProduitUnite.KG,
    notes: "Insecticide colza, pommes de terre",
    sourceCatalogue: SRC_OSAV,
  },
  {
    code: "aq-phyto-axial-50",
    categorie: ProduitCategorie.PHYTO,
    libelle: "Axial 50 (pinoxaden)",
    fournisseur: "Syngenta",
    unite: ProduitUnite.L,
    notes: "Anti-graminées céréales",
    sourceCatalogue: SRC_OSAV,
  },

  // ==================================================================
  // EXTENSION 2026 — Cultures complémentaires
  // Couverture demandée : herbages, jachères, pommes de terre, légumes,
  // légumineuses, vignes, vergers, plantes spéciales. Sources : Agridea
  // (catalogue Mst), Agroscope, swissgranum, OFAG OPD-CH-2026.
  // ==================================================================

  // ---- Petites céréales & pseudocéréales ---------------------------
  {
    code: "aq-sem-amidonnier",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Amidonnier (Triticum dicoccum)",
    fournisseur: "Agroscope",
    especeCode: "ble_panifiable",
    unite: ProduitUnite.KG,
    notes: "Céréale ancienne, niche boulangerie spéciale",
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-engrain",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Engrain (Triticum monococcum)",
    fournisseur: "Agroscope",
    especeCode: "ble_panifiable",
    unite: ProduitUnite.KG,
    notes: "Céréale ancienne, biscuiterie",
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-sarrasin",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Sarrasin (Fagopyrum esculentum)",
    fournisseur: "DSP / OH",
    especeCode: "sarrasin",
    unite: ProduitUnite.KG,
    notes: "Pseudocéréale, sans gluten, intéressante pour SPB",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-millet",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Millet (Panicum miliaceum)",
    fournisseur: "Agroscope",
    especeCode: "millet",
    unite: ProduitUnite.KG,
    notes: "Culture estivale, très peu de besoins en eau",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-quinoa",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Quinoa (Chenopodium quinoa)",
    fournisseur: "DSP",
    especeCode: "quinoa",
    unite: ProduitUnite.KG,
    notes: "Pseudocéréale, niche bio",
    sourceCatalogue: SRC_AGRIDEA,
  },

  // ---- Légumineuses --------------------------------------------------
  {
    code: "aq-sem-pois-prot-protecta",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pois protéagineux Protecta",
    fournisseur: "DSP / Fenaco",
    especeCode: "pois_proteagineux",
    unite: ProduitUnite.KG,
    notes: "Variété de printemps, fixation symbiotique",
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-pois-prot-astronaute",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pois protéagineux Astronaute",
    fournisseur: "Agroscope",
    especeCode: "pois_proteagineux",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-pois-prot-mythic",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pois protéagineux Mythic",
    fournisseur: "DSP",
    especeCode: "pois_proteagineux",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-feverole-fanfare",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Féverole Fanfare",
    fournisseur: "DSP",
    especeCode: "feverole",
    unite: ProduitUnite.KG,
    notes: "Variété de printemps, fixation symbiotique élevée",
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-feverole-tiffany",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Féverole Tiffany (hiver)",
    fournisseur: "DSP",
    especeCode: "feverole",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-soja-protena",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Soja Protena",
    fournisseur: "Agroscope",
    especeCode: "soja",
    unite: ProduitUnite.KG,
    notes: "Variété précoce, swissgranum suisse",
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-soja-aurelina",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Soja Aurelina",
    fournisseur: "Agroscope",
    especeCode: "soja",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-soja-galice",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Soja Galice",
    fournisseur: "Agroscope",
    especeCode: "soja",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_SG,
  },
  {
    code: "aq-sem-lupin-feodora",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Lupin doux Feodora",
    fournisseur: "DSP",
    especeCode: "lupin",
    unite: ProduitUnite.KG,
    notes: "Lupin blanc, alimentation animale + humaine",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-lentille-anicia",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Lentille verte Anicia",
    fournisseur: "Agroscope",
    especeCode: "lentille",
    unite: ProduitUnite.KG,
    notes: "Niche bio, fixation symbiotique modérée",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-vesce",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Vesce commune (Vicia sativa)",
    fournisseur: "Agroscope",
    especeCode: "vesce",
    unite: ProduitUnite.KG,
    notes: "Engrais vert, mélanges intercultures",
    sourceCatalogue: SRC_MST,
  },

  // ---- Pommes de terre (Variétés Agroscope/swisspatat) -------------
  {
    code: "aq-sem-pdt-charlotte",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pommes de terre Charlotte",
    fournisseur: "swisspatat",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    notes: "Chair ferme, salade, vapeur",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-pdt-agria",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pommes de terre Agria",
    fournisseur: "swisspatat",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    notes: "Chair farineuse, frites, purée",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-pdt-annabelle",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pommes de terre Annabelle",
    fournisseur: "swisspatat",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    notes: "Chair ferme, précoce",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-pdt-lady-christl",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pommes de terre Lady Christl",
    fournisseur: "swisspatat",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    notes: "Précoce, marché frais",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-pdt-ditta",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pommes de terre Ditta",
    fournisseur: "swisspatat",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    notes: "Chair ferme à demi-ferme, polyvalente",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-pdt-victoria",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pommes de terre Victoria",
    fournisseur: "swisspatat",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-pdt-erika",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pommes de terre Erika",
    fournisseur: "swisspatat",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-pdt-gourmandine",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pommes de terre Gourmandine",
    fournisseur: "swisspatat",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    notes: "Chair ferme, premium",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-pdt-jelly",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pommes de terre Jelly",
    fournisseur: "swisspatat",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    notes: "Frites/chips industrielles",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-pdt-laura",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pommes de terre Laura",
    fournisseur: "swisspatat",
    especeCode: "pomme_de_terre",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_AGRIDEA,
  },

  // ---- Mélanges prairies Agroscope (Mst 2025-2028) ------------------
  {
    code: "aq-sem-mst-200",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 200 — Trèfle violet pur (1 an)",
    fournisseur: "Agroscope / eADCF",
    especeCode: "trefle_violet",
    unite: ProduitUnite.KG,
    notes: "Prairie temporaire 1 an, légumineuse pure",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-mst-220",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 220 — Trèfle d'Alexandrie + Italien",
    fournisseur: "Agroscope / eADCF",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    notes: "Engrais vert d'été, étouffe le rumex",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-mst-240",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 240 — Ray-grass d'Italie",
    fournisseur: "Agroscope / eADCF",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    notes: "Prairie 1 an riche en énergie",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-mst-320",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 320 — Trèfle violet + Ray-grass d'Italie (2 ans)",
    fournisseur: "Agroscope / eADCF",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-mst-330",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 330 — Trèfle violet + Ray-grass anglais (2-3 ans)",
    fournisseur: "Agroscope / eADCF",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-mst-431",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 431 — Luzerne + graminées (3 ans)",
    fournisseur: "Agroscope / eADCF",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    notes: "Luzerne dominante, sols profonds",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-mst-440",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 440 — Trèfles + graminées (3-4 ans)",
    fournisseur: "Agroscope / eADCF",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    notes: "Mélange polyvalent intensif/extensif",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-mst-442",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 442 — Variante trèfle blanc dominant",
    fournisseur: "Agroscope / eADCF",
    especeCode: "prairie_temporaire",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-mst-462",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 462 — Prairie permanente standard",
    fournisseur: "Agroscope / eADCF",
    especeCode: "prairie_permanente",
    unite: ProduitUnite.KG,
    notes: "Mélange polyvalent durable, plaine",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-mst-481",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 481 — Prairie longue durée intensive",
    fournisseur: "Agroscope / eADCF",
    especeCode: "paturage_intensif",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-mst-482",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 482 — Prairie longue durée pâturage",
    fournisseur: "Agroscope / eADCF",
    especeCode: "paturage_intensif",
    unite: ProduitUnite.KG,
    notes: "Tolère le pâturage intensif",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-mst-600",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 600 — Mélange diversité (faune + biodiversité)",
    fournisseur: "Agroscope / eADCF",
    especeCode: "prairie_extensive",
    unite: ProduitUnite.KG,
    notes: "Surface de promotion biodiversité (SPB)",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-mst-610",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Mst 610 — Prairie peu intensive zone montagne",
    fournisseur: "Agroscope / eADCF",
    especeCode: "prairie_extensive",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },

  // ---- Cultures fourragères pures (composantes de mélange) ----------
  {
    code: "aq-sem-luzerne-orca",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Luzerne Orca",
    fournisseur: "Agroscope",
    especeCode: "luzerne",
    unite: ProduitUnite.KG,
    notes: "Variété résistante, riche en protéines",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-luzerne-galaxie",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Luzerne Galaxie",
    fournisseur: "Agroscope",
    especeCode: "luzerne",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-trefle-blanc-milkanova",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Trèfle blanc Milkanova",
    fournisseur: "Agroscope",
    especeCode: "trefle_blanc",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-trefle-violet-milvus",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Trèfle violet Milvus",
    fournisseur: "Agroscope",
    especeCode: "trefle_violet",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-rga-arvicola",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Ray-grass anglais Arvicola",
    fournisseur: "Agroscope",
    especeCode: "ray_grass_anglais",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-rgi-oryx",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Ray-grass d'Italie Oryx",
    fournisseur: "Agroscope",
    especeCode: "ray_grass_italie",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-fetuque-elevee",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Fétuque élevée Belfine",
    fournisseur: "Agroscope",
    especeCode: "fetuque_elevee",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-dactyle",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Dactyle Diplomat",
    fournisseur: "Agroscope",
    especeCode: "dactyle",
    unite: ProduitUnite.KG,
    notes: "Tolère sécheresse",
    sourceCatalogue: SRC_MST,
  },

  // ---- Surfaces de promotion biodiversité (SPB) & jachères ----------
  {
    code: "aq-sem-jachere-florale-ufa",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Jachère florale (mélange UFA Wildblumen)",
    fournisseur: "UFA Samen",
    especeCode: "jachere_florale",
    unite: ProduitUnite.KG,
    notes: "SPB type 8, durée 2-8 ans, fertilisation interdite",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-jachere-tournante-ufa",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Jachère tournante (mélange UFA)",
    fournisseur: "UFA Samen",
    especeCode: "jachere_tournante",
    unite: ProduitUnite.KG,
    notes: "SPB type 7, durée 1-3 ans",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-bande-fleurie-ufa",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Bande fleurie (mélange UFA pollinisateurs)",
    fournisseur: "UFA Samen",
    especeCode: "bande_fleurie",
    unite: ProduitUnite.KG,
    notes: "SPB type 17, contributions OPD majorées",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-prairie-extensive",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Prairie extensive (Salvia Zone 1)",
    fournisseur: "UFA Samen",
    especeCode: "prairie_extensive",
    unite: ProduitUnite.KG,
    notes: "SPB type 1, fertilisation interdite, fauche dès 15 juin",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-prairie-peu-intensive",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Prairie peu intensive (Salvia Zone 2)",
    fournisseur: "UFA Samen",
    especeCode: "prairie_peu_intensive",
    unite: ProduitUnite.KG,
    notes: "SPB type 2, fauche dès 15 juin, fumure limitée",
    sourceCatalogue: SRC_MST,
  },
  {
    code: "aq-sem-surface-litiere",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Surface à litière (Salvia humide)",
    fournisseur: "UFA Samen",
    especeCode: "surface_litiere",
    unite: ProduitUnite.KG,
    notes: "SPB type 6, sols humides, fauche tardive",
    sourceCatalogue: SRC_MST,
  },

  // ---- Plantes industrielles & spéciales ----------------------------
  {
    code: "aq-sem-lin-oleagineux",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Lin oléagineux Niagara",
    fournisseur: "DSP",
    especeCode: "lin_oleagineux",
    unite: ProduitUnite.KG,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-chanvre-finola",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Chanvre industriel Finola",
    fournisseur: "Agroscope",
    especeCode: "chanvre",
    unite: ProduitUnite.KG,
    notes: "THC < 1%, autorisé Suisse, fibres + graines",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-tabac",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Tabac Burley",
    fournisseur: "swisstabac",
    especeCode: "tabac",
    unite: ProduitUnite.DOSE,
    notes: "Plants en mottes, sous contrat swisstabac",
    sourceCatalogue: SRC_AGRIDEA,
  },

  // ---- Légumes plein champ (variétés courantes CH) ------------------
  {
    code: "aq-sem-carotte-nantaise",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Carotte Nantaise (Bolero F1)",
    fournisseur: "Vilmorin",
    especeCode: "carotte",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-sem-oignon-jaune",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Oignon jaune (Hytech F1)",
    fournisseur: "Vilmorin",
    especeCode: "oignon",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-sem-poireau-bleu-de-solaise",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Poireau Bleu de Solaise",
    fournisseur: "Vilmorin",
    especeCode: "poireau",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-sem-chou-blanc",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Chou blanc (Bartolo F1)",
    fournisseur: "Vilmorin",
    especeCode: "chou_blanc",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-sem-chou-fleur",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Chou-fleur (Cabrera F1)",
    fournisseur: "Vilmorin",
    especeCode: "chou_fleur",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-sem-courge-musquee",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Courge musquée (Butternut Waltham)",
    fournisseur: "Vilmorin",
    especeCode: "courge",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-sem-courgette",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Courgette verte (Defender F1)",
    fournisseur: "Vilmorin",
    especeCode: "courgette",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-sem-betterave-rouge",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Betterave rouge (Pablo F1)",
    fournisseur: "Vilmorin",
    especeCode: "betterave_rouge",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-sem-salade-batavia",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Salade Batavia (Madrilène)",
    fournisseur: "Vilmorin",
    especeCode: "salade",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_LANDOR,
  },
  {
    code: "aq-sem-asperge",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Asperge verte Backlim",
    fournisseur: "Limgroup",
    especeCode: "asperge",
    unite: ProduitUnite.DOSE,
    notes: "Plantation pluriannuelle (~10 ans)",
    sourceCatalogue: SRC_LANDOR,
  },

  // ---- Vigne (sélection cépages CH) ---------------------------------
  {
    code: "aq-sem-vigne-chasselas",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Vigne Chasselas (Fendant)",
    fournisseur: "ViVino / DRAVS",
    especeCode: "vigne",
    unite: ProduitUnite.DOSE,
    notes: "Cépage emblématique romand, plants greffés",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-vigne-pinot-noir",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Vigne Pinot Noir",
    fournisseur: "ViVino / DRAVS",
    especeCode: "vigne",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-vigne-gamay",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Vigne Gamay",
    fournisseur: "ViVino / DRAVS",
    especeCode: "vigne",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-vigne-gamaret",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Vigne Gamaret",
    fournisseur: "ViVino / Agroscope",
    especeCode: "vigne",
    unite: ProduitUnite.DOSE,
    notes: "Cépage rouge créé Agroscope, rusticité élevée",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-vigne-muller-thurgau",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Vigne Müller-Thurgau (Riesling-Sylvaner)",
    fournisseur: "ViVino / DRAVS",
    especeCode: "vigne",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_AGRIDEA,
  },

  // ---- Vergers (variétés de table CH) -------------------------------
  {
    code: "aq-sem-pommier-gala",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pommier Gala",
    fournisseur: "Lubera / Pépinières",
    especeCode: "verger_pommes",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-pommier-boskoop",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pommier Boskoop",
    fournisseur: "Lubera / Pépinières",
    especeCode: "verger_pommes",
    unite: ProduitUnite.DOSE,
    notes: "Variété rustique, pomme de garde",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-pommier-gravenstein",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pommier Gravenstein",
    fournisseur: "Lubera / Pépinières",
    especeCode: "verger_pommes",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-poirier-conference",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Poirier Conférence",
    fournisseur: "Lubera",
    especeCode: "verger_poires",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-poirier-williams",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Poirier Williams",
    fournisseur: "Lubera",
    especeCode: "verger_poires",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-cerisier-kordia",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Cerisier Kordia",
    fournisseur: "Lubera",
    especeCode: "verger_cerises",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-pruneau-fellenberg",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Pruneau Fellenberg",
    fournisseur: "Lubera",
    especeCode: "verger_prunes",
    unite: ProduitUnite.DOSE,
    notes: "Variété typiquement suisse, pruneaux secs",
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-abricotier-luizet",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Abricotier Luizet (variété valaisanne)",
    fournisseur: "Lubera / VSAGA",
    especeCode: "verger_abricots",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-fraisier-elsanta",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Fraisier Elsanta",
    fournisseur: "Lubera",
    especeCode: "petits_fruits_fraises",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_AGRIDEA,
  },
  {
    code: "aq-sem-framboisier-tulameen",
    categorie: ProduitCategorie.SEMENCE,
    libelle: "Framboisier Tulameen",
    fournisseur: "Lubera",
    especeCode: "petits_fruits_framboises",
    unite: ProduitUnite.DOSE,
    sourceCatalogue: SRC_AGRIDEA,
  },

  // ==================================================================
  // PRESTATIONS — Services de travaux à façon (Fabien 2026-05-14)
  // Unités corrigées : UNITE (= balle) pour bottelage ; HA pour les
  // prestations à l'hectare ; M3/T pour les épandages volumétriques.
  // ==================================================================
  {
    code: "aq-prest-bottelage-balle-ronde-sec",
    categorie: ProduitCategorie.PRESTATION,
    libelle: "Bottelage balle ronde de sec",
    unite: ProduitUnite.UNITE,
    notes: "Prix à la balle. Inclut tracteur + presse + chauffeur.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-prest-bottelage-balle-ronde-enrubannage",
    categorie: ProduitCategorie.PRESTATION,
    libelle: "Bottelage balle ronde enrubannée",
    unite: ProduitUnite.UNITE,
    notes: "Bottelage + enrubanneuse. Prix à la balle.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-prest-bottelage-balle-carree",
    categorie: ProduitCategorie.PRESTATION,
    libelle: "Bottelage balle carrée (HD)",
    unite: ProduitUnite.UNITE,
    notes: "Petites balles haute densité. Prix à la balle.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-prest-endainage",
    categorie: ProduitCategorie.PRESTATION,
    libelle: "Endainage (mise en andains)",
    unite: ProduitUnite.HA,
    notes: "Andaineur soleil/rotative. Facturation à l'hectare.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-prest-fauchage",
    categorie: ProduitCategorie.PRESTATION,
    libelle: "Fauchage",
    unite: ProduitUnite.HA,
    notes: "Faucheuse à disques ou conditionneuse. À l'hectare.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-prest-pirouettage",
    categorie: ProduitCategorie.PRESTATION,
    libelle: "Pirouettage (fanage)",
    unite: ProduitUnite.HA,
    notes: "Fanage de fourrage en andains. À l'hectare.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-prest-ensilage-mais",
    categorie: ProduitCategorie.PRESTATION,
    libelle: "Ensilage de maïs (récolte ensileuse)",
    unite: ProduitUnite.HA,
    notes: "Ensileuse automotrice + remorques. À l'hectare.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-prest-ensilage-herbe",
    categorie: ProduitCategorie.PRESTATION,
    libelle: "Ensilage d'herbe",
    unite: ProduitUnite.HA,
    notes: "Ensilage prairie. À l'hectare.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-prest-moisson-cereales",
    categorie: ProduitCategorie.PRESTATION,
    libelle: "Moisson céréales",
    unite: ProduitUnite.HA,
    notes: "Moissonneuse-batteuse. À l'hectare.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-prest-semis-direct",
    categorie: ProduitCategorie.PRESTATION,
    libelle: "Semis (à façon)",
    unite: ProduitUnite.HA,
    notes: "Semoir + tracteur. À l'hectare.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-prest-epandage-lisier",
    categorie: ProduitCategorie.PRESTATION,
    libelle: "Épandage lisier",
    unite: ProduitUnite.M3,
    notes: "Tonne à lisier + pendillard ou enfouisseur. Au m³.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-prest-epandage-fumier",
    categorie: ProduitCategorie.PRESTATION,
    libelle: "Épandage fumier",
    unite: ProduitUnite.T,
    notes: "Épandeur à fumier. À la tonne.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-prest-main-oeuvre",
    categorie: ProduitCategorie.PRESTATION,
    libelle: "Main d'œuvre (heure)",
    unite: ProduitUnite.HEURE,
    notes: "Heure de main d'œuvre seule (sans machine).",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },

  // ==================================================================
  // TRAVAUX DU SOL — Prestations à l'hectare
  // ==================================================================
  {
    code: "aq-ts-labour",
    categorie: ProduitCategorie.TRAVAIL_SOL,
    libelle: "Labour",
    unite: ProduitUnite.HA,
    notes: "Charrue. À l'hectare.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-ts-dechaumage",
    categorie: ProduitCategorie.TRAVAIL_SOL,
    libelle: "Déchaumage",
    unite: ProduitUnite.HA,
    notes: "Déchaumeur à disques ou à dents. À l'hectare.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-ts-hersage",
    categorie: ProduitCategorie.TRAVAIL_SOL,
    libelle: "Hersage / herse rotative",
    unite: ProduitUnite.HA,
    notes: "Préparation lit de semence. À l'hectare.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
  {
    code: "aq-ts-sous-solage",
    categorie: ProduitCategorie.TRAVAIL_SOL,
    libelle: "Sous-solage",
    unite: ProduitUnite.HA,
    notes: "Décompactage profond. À l'hectare.",
    sourceCatalogue: "Agri Qodo — prestations standard",
  },
];

async function seed(): Promise<void> {
  for (const p of PRODUITS) {
    const data = {
      libelle: p.libelle,
      fournisseur: p.fournisseur ?? null,
      marque: p.marque ?? null,
      numeroOfficiel: p.numeroOfficiel ?? null,
      especeCode: p.especeCode ?? null,
      tauxN: p.tauxN ?? null,
      tauxP: p.tauxP ?? null,
      tauxK: p.tauxK ?? null,
      unite: p.unite ?? ProduitUnite.KG,
      notes: p.notes ?? null,
      sourceCatalogue: p.sourceCatalogue,
      actif: true,
    };
    await prisma.produit.upsert({
      where: { code: p.code },
      update: data,
      create: { tenantId: null, code: p.code, categorie: p.categorie, ...data },
    });
  }
  const counts = await prisma.produit.groupBy({
    by: ["categorie"],
    where: { tenantId: null },
    _count: { _all: true },
  });
  console.log("Catalogue Produits global seeded :");
  for (const c of counts) {
    console.log(`  ${c.categorie}: ${c._count._all}`);
  }
}

seed()
  .catch((e: unknown) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => {
    void prisma.$disconnect();
  });
