import type { ThirdPartyClient, WorkOrder } from './travaux.types';

/**
 * Clients tiers du Domaine Darval (démo).
 */
export const CLIENTS_MOCK: ReadonlyArray<ThirdPartyClient> = [
  {
    id: 'C-001',
    name: 'Famille Pittet — Bercher',
    city: 'Bercher, VD',
    email: 'pittet.ferme@bluewin.ch',
    phone: '+41 21 887 12 34',
    notes: 'Voisin direct, paiement à 30 jours',
    active: true,
  },
  {
    id: 'C-002',
    name: 'Domaine de Goumoëns Sàrl',
    city: 'Goumoëns-la-Ville, VD',
    email: 'admin@domaine-goumoens.ch',
    vatNumber: 'CHE-123.456.789',
    active: true,
  },
  {
    id: 'C-003',
    name: 'Commune d’Échallens',
    city: 'Échallens, VD',
    email: 'travaux@echallens.ch',
    notes: 'Entretien talus chemin agricole',
    active: true,
  },
  {
    id: 'C-004',
    name: 'Hofstetter SA',
    city: 'Bottens, VD',
    email: 'compta@hofstetter-agri.ch',
    vatNumber: 'CHE-987.654.321',
    active: true,
  },
];

/**
 * Bons de travaux mock — au nouveau format multi-lignes + multi-saisies temps.
 */
export const WORK_ORDERS_MOCK: ReadonlyArray<WorkOrder> = [
  {
    id: 'WO-001',
    date: '2026-04-12',
    clientId: 'C-001',
    description: 'Préparation parcelle "Combe" pour semis maïs',
    machine: 'John Deere 6155R',
    status: 'invoiced',
    priority: '1',
    userIds: ['U-002'],
    invoiceRef: 'F2026-0028',
    invoicedAt: '2026-04-20',
    lines: [
      {
        id: 'WL-001-1',
        workType: 'plowing',
        description: 'Charrue 4 socs, profondeur 28 cm',
        surfaceHa: 2.8,
        durationHours: 3.5,
        billingUnit: 'hectare',
        unitRateChf: 220,
        totalChf: 616,
      },
      {
        id: 'WL-001-2',
        workType: 'rolling',
        description: 'Roulage de finition',
        surfaceHa: 2.8,
        durationHours: 1.2,
        billingUnit: 'hectare',
        unitRateChf: 60,
        totalChf: 168,
      },
    ],
    timeEntries: [
      {
        id: 'WT-001-1',
        operatorId: 'U-002',
        date: '2026-04-12',
        startTime: '07:30',
        endTime: '11:00',
        durationHours: 3.5,
        lineId: 'WL-001-1',
      },
      {
        id: 'WT-001-2',
        operatorId: 'U-002',
        date: '2026-04-12',
        startTime: '14:00',
        endTime: '15:15',
        durationHours: 1.25,
        lineId: 'WL-001-2',
      },
    ],
  },
  {
    id: 'WO-002',
    date: '2026-04-15',
    clientId: 'C-001',
    description: 'Semis maïs ensilage variété LG31.245',
    machine: 'Kverneland Optima HD-e',
    status: 'invoiced',
    priority: '1',
    userIds: ['U-002'],
    invoiceRef: 'F2026-0029',
    invoicedAt: '2026-04-22',
    lines: [
      {
        id: 'WL-002-1',
        workType: 'sowing-precision',
        surfaceHa: 2.8,
        durationHours: 2.0,
        billingUnit: 'hectare',
        unitRateChf: 220,
        totalChf: 616,
      },
    ],
    timeEntries: [
      {
        id: 'WT-002-1',
        operatorId: 'U-002',
        date: '2026-04-15',
        durationHours: 2.0,
      },
    ],
  },
  {
    id: 'WO-003',
    date: '2026-05-08',
    clientId: 'C-002',
    description: 'Fauche + fanage + andainage prairie naturelle',
    status: 'done',
    priority: '1',
    userIds: ['U-003'],
    lines: [
      {
        id: 'WL-003-1',
        workType: 'mowing',
        surfaceHa: 1.8,
        durationHours: 1.5,
        billingUnit: 'hectare',
        unitRateChf: 120,
        totalChf: 216,
      },
      {
        id: 'WL-003-2',
        workType: 'tedding',
        surfaceHa: 1.8,
        durationHours: 0.8,
        billingUnit: 'hectare',
        unitRateChf: 55,
        totalChf: 99,
      },
      {
        id: 'WL-003-3',
        workType: 'raking',
        surfaceHa: 1.8,
        durationHours: 0.7,
        billingUnit: 'hectare',
        unitRateChf: 55,
        totalChf: 99,
      },
    ],
    timeEntries: [
      {
        id: 'WT-003-1',
        operatorId: 'U-003',
        date: '2026-05-08',
        startTime: '06:00',
        endTime: '09:00',
        durationHours: 3.0,
      },
    ],
  },
  {
    id: 'WO-004',
    date: '2026-05-14',
    clientId: 'C-003',
    description: 'Broyage talus chemin de la Combe',
    status: 'done',
    priority: '1',
    userIds: ['U-003'],
    lines: [
      {
        id: 'WL-004-1',
        workType: 'mulching',
        durationHours: 4.0,
        billingUnit: 'heure',
        unitRateChf: 130,
        totalChf: 520,
      },
    ],
    timeEntries: [
      {
        id: 'WT-004-1',
        operatorId: 'U-002',
        date: '2026-05-14',
        startTime: '13:00',
        endTime: '17:00',
        durationHours: 4.0,
      },
    ],
  },
  {
    id: 'WO-005',
    date: '2026-05-22',
    clientId: 'C-004',
    description: 'Épandage 35 m³ lisier sur prairie',
    status: 'planned',
    priority: '2',
    userIds: ['U-002'],
    lines: [
      {
        id: 'WL-005-1',
        workType: 'spreading-slurry',
        surfaceHa: 3.2,
        durationHours: 2.5,
        billingUnit: 'hectare',
        unitRateChf: 280,
        totalChf: 896,
      },
    ],
    timeEntries: [],
  },
];
