-- Extension des catégories produit (Fabien 2026-05-14) : ajout de
-- PRESTATION (bottelage, endainage, ensilage…), TRAVAIL_SOL, RECOLTE,
-- IRRIGATION, CARBURANT, PIECES_MATERIEL.

ALTER TYPE "ProduitCategorie" ADD VALUE IF NOT EXISTS 'PRESTATION';
ALTER TYPE "ProduitCategorie" ADD VALUE IF NOT EXISTS 'TRAVAIL_SOL';
ALTER TYPE "ProduitCategorie" ADD VALUE IF NOT EXISTS 'RECOLTE';
ALTER TYPE "ProduitCategorie" ADD VALUE IF NOT EXISTS 'IRRIGATION';
ALTER TYPE "ProduitCategorie" ADD VALUE IF NOT EXISTS 'CARBURANT';
ALTER TYPE "ProduitCategorie" ADD VALUE IF NOT EXISTS 'PIECES_MATERIEL';
